swagger: "2.0"
info:
  version: 0.0.1
  title: Kanban
  description: Kanban
basePath: /api/v1
tags:
  - name: Balance
    description: Account balance endpoints
  - name: Network Information
    description: FAB Network status

consumes:
  - application/json
produces:
  - application/json

definitions:
  BalanceBody:
    type: object
    title: balance
    required:
      - account
    properties:
      account:
        type: string
        description: Account ID
      balance:
        type: integer
        description: Account balance

paths:
  /network:
    get:
      tags:
        - Network Information
      description: Fetch current network info
      responses:
        200:
          description: Returns current network information
  /peer-info:
      get:
        tags:
          - Network Information
        description: Fetch peer info
        responses:
          200:
            description: Returns connected peer information
  /balance:
    get:
      tags:
        - Balance
      description: Fetch balance of all accounts
      responses:
        200:
          description: Returns balance of all accounts
    post:
      tags:
        - Balance
      description: Create a new account with balance
      parameters:
        - name: body
          in: body
          description: Account with balance info
          required: true
          schema: 
            $ref: "#/definitions/BalanceBody"
      responses:
        200:
          description: Successfully created account

  /balance/{account}:
    get:
      tags:
        - Balance
      parameters:
        - name: account
          in: path
          required: true
          description: The account of user wallet
          type: string
      responses:
        200:
          description: Return the balance of specific account
        404:
          description: Account not found
